package bankingsystem;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ACER
 */
public class Debit extends javax.swing.JFrame {

    /**
     * Creates new form Debit
     */
    public Debit() {
        initComponents();
        setLocation(150,5);
        setTitle("DEBIT");
        setSize(1080,750);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edtFn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtADS = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        edtTP = new javax.swing.JTextField();
        edtEM = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        edtMS = new javax.swing.JComboBox<>();
        edtTA = new javax.swing.JComboBox<>();
        edtGR = new javax.swing.JComboBox<>();
        edtDOB = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        edtBC = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(37, 44, 55));
        jPanel1.setPreferredSize(new java.awt.Dimension(1060, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Debit Card Application Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 450, 50));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FULL NAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 94, -1, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATE OF BIRTH");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 158, 140, 33));

        edtFn.setBackground(new java.awt.Color(204, 204, 204));
        edtFn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtFnActionPerformed(evt);
            }
        });
        jPanel1.add(edtFn, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 95, 240, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GENDER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 215, 80, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ADDRESS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 40));

        edtADS.setBackground(new java.awt.Color(204, 204, 204));
        edtADS.setColumns(20);
        edtADS.setRows(5);
        jScrollPane1.setViewportView(edtADS);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 302, 240, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MARITIAL STATUS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 416, -1, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TELEPHONE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EMAIL");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 546, 60, 30));

        edtTP.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(edtTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 481, 240, 30));

        edtEM.setBackground(new java.awt.Color(204, 204, 204));
        edtEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEMActionPerformed(evt);
            }
        });
        jPanel1.add(edtEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 547, 240, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TYPE OF ACCOUNT");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 94, -1, 29));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("BRANCH CODE");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 159, -1, 30));

        jButton1.setBackground(new java.awt.Color(248, 198, 23));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(37, 44, 55));
        jButton1.setText("SUBMIT");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 632, 120, 30));

        edtMS.setBackground(new java.awt.Color(204, 204, 204));
        edtMS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        edtMS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Married", "Single" }));
        jPanel1.add(edtMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 417, 240, 30));

        edtTA.setBackground(new java.awt.Color(204, 204, 204));
        edtTA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        edtTA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saving", "Current" }));
        edtTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtTAActionPerformed(evt);
            }
        });
        jPanel1.add(edtTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 94, 240, 30));

        edtGR.setBackground(new java.awt.Color(204, 204, 204));
        edtGR.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        edtGR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        jPanel1.add(edtGR, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 215, 240, 30));

        edtDOB.setBackground(new java.awt.Color(204, 204, 204));
        edtDOB.setText("YYYY-DD-MM");
        edtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDOBActionPerformed(evt);
            }
        });
        jPanel1.add(edtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 160, 240, 30));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(996, 0, 70, 30));

        edtBC.setBackground(new java.awt.Color(204, 204, 204));
        edtBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtBCActionPerformed(evt);
            }
        });
        jPanel1.add(edtBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 160, 240, 30));

        jPanel3.setBackground(new java.awt.Color(248, 198, 23));
        jPanel3.setFocusable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtBCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtBCActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.show();
        dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void edtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDOBActionPerformed

    private void edtTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtTAActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","root");
            String sql="insert into debit values(?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1,edtFn.getText());
            pst.setString(2,edtDOB.getText());
            pst.setString(3,String.valueOf(edtGR.getSelectedItem()));
            pst.setString(4,edtADS.getText());
            pst.setString(5,String.valueOf(edtMS.getSelectedItem()));
            pst.setString(6,edtTP.getText());
            pst.setString(7,edtEM.getText());
            pst.setString(8,String.valueOf(edtTA.getSelectedItem()));
            pst.setString(9,edtBC.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Form Submitted");
            conn.close();
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void edtEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEMActionPerformed

    private void edtFnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtFnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtFnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Debit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Debit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Debit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Debit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Debit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea edtADS;
    private javax.swing.JTextField edtBC;
    private javax.swing.JTextField edtDOB;
    private javax.swing.JTextField edtEM;
    private javax.swing.JTextField edtFn;
    private javax.swing.JComboBox<String> edtGR;
    private javax.swing.JComboBox<String> edtMS;
    private javax.swing.JComboBox<String> edtTA;
    private javax.swing.JTextField edtTP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
