/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankingsystem;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Sneha
 */
public class Loan extends javax.swing.JFrame {

    /**
     * Creates new form Loan
     */
    public Loan() {
        initComponents();
        setLocation(150,5);
        setSize(1060,750);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        edtMaritalbox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        edtName = new javax.swing.JTextField();
        edtDesiredamount = new javax.swing.JTextField();
        edtContact = new javax.swing.JTextField();
        edtEmail = new javax.swing.JTextField();
        edtDob = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edtAnnualincome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        edtAddress = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        edtOccupation = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        edtExperience = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        edtMonthlyincome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edtLoanbox = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(37, 44, 55));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Desired Loan Amount :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 151, 190, -1));

        edtMaritalbox.setBackground(new java.awt.Color(204, 204, 204));
        edtMaritalbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married" }));
        jPanel2.add(edtMaritalbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 429, 240, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Full Name :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 90, 143, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact Number :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 213, 150, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("E-Mail ID :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 282, 120, 31));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date Of Birth :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 351, 160, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Marital Status :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 428, 130, 30));

        edtName.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(edtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 91, 240, 30));

        edtDesiredamount.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(edtDesiredamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 147, 240, 30));

        edtContact.setBackground(new java.awt.Color(204, 204, 204));
        edtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtContactActionPerformed(evt);
            }
        });
        jPanel2.add(edtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 214, 240, 30));

        edtEmail.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(edtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 283, 240, 30));

        edtDob.setBackground(new java.awt.Color(204, 204, 204));
        edtDob.setText("dd/mm/yyyy");
        jPanel2.add(edtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 352, 240, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Annual Income :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 160, 31));

        edtAnnualincome.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(edtAnnualincome, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 99, 240, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Address :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 502, 109, 30));

        edtAddress.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(edtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 502, 240, 73));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Occupation :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 151, 110, -1));

        edtOccupation.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(edtOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 157, 240, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Years of experience :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 213, 180, 30));

        edtExperience.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(edtExperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 214, 240, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Gross monthly income:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 282, 190, 30));

        edtMonthlyincome.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(edtMonthlyincome, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 283, 240, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Loan will be used for :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 351, 170, 30));

        edtLoanbox.setBackground(new java.awt.Color(204, 204, 204));
        edtLoanbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HOME LOAN", "PERSONAL LOAN", "EDUCATION LOAN", "BUSINESS LOAN", "INVESTMENT" }));
        jPanel2.add(edtLoanbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(821, 352, 240, 30));

        btnSubmit.setBackground(new java.awt.Color(248, 198, 23));
        btnSubmit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(37, 44, 55));
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel2.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 637, 120, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Loan Application Form");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, 40));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 70, 40));

        jPanel3.setBackground(new java.awt.Color(248, 198, 23));
        jPanel3.setFocusable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1070, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtContactActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","root");

            String sql = "insert into loan values(?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1,edtName.getText());
            pstmt.setInt(2,Integer.parseInt(edtDesiredamount.getText()));
            pstmt.setString(3,edtContact.getText());
            pstmt.setString(4,edtEmail.getText());
            pstmt.setString(5,edtDob.getText());
            String value = (String)edtMaritalbox.getSelectedItem();
            pstmt.setString(6,value);
            pstmt.setString(7,edtAddress.getText());
            pstmt.setInt(8,Integer.parseInt(edtAnnualincome.getText()));
            pstmt.setString(9,edtOccupation.getText());
            pstmt.setString(10,edtExperience.getText());
            pstmt.setString(11,edtMonthlyincome.getText());
            String loan = (String) edtLoanbox.getSelectedItem();
            pstmt.setString(12,loan);
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "FORM SUBMITTED");

            conn.close();
            LoanSubmission obj = new LoanSubmission();
            obj.show();
            dispose();

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        HomePage home = new HomePage();
        home.show();
        dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTextField edtAddress;
    private javax.swing.JTextField edtAnnualincome;
    private javax.swing.JTextField edtContact;
    private javax.swing.JTextField edtDesiredamount;
    private javax.swing.JTextField edtDob;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtExperience;
    private javax.swing.JComboBox<String> edtLoanbox;
    private javax.swing.JComboBox<String> edtMaritalbox;
    private javax.swing.JTextField edtMonthlyincome;
    private javax.swing.JTextField edtName;
    private javax.swing.JTextField edtOccupation;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    private void SetCentre(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
