/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Manish Sharma
 */
public class bookingooty extends javax.swing.JFrame {

    /**
     * Creates new form bookingooty
     */
    public bookingooty() {
        initComponents();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Travelmanagement","root","Manish6022@");

            String query="select * from Login order by id desc limit 1";
            Statement ps=con.createStatement();
            ResultSet rs=ps.executeQuery(query);
             StringBuilder count=new StringBuilder();
           StringBuilder sname=new StringBuilder();
           StringBuilder scontact=new StringBuilder();
            if(rs.next())
            {   
                      count.append("").append(rs.getString("id"));
                       count.append("\n");
                 sname.append("").append(rs.getString("firstname")); 
                  sname.append("\n");
                    tname.setText(sname.toString());
                      sname.append(" ").append(rs.getString("lastname")); 
                  sname.append("\n");
                    tname.setText(sname.toString());
                    scontact.append("").append(rs.getString("contact"));
                    scontact.append("\n");
                    tcontact.setText(scontact.toString());
                    
                }
            
           
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,"error");
    }
        lprice.setText("Rs 0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lprice = new javax.swing.JLabel();
        tperson = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tpackage = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tdate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tcontact = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tdestination = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        tname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        tto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(570, 650));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Your Dream Vacation awaits. CONFORM NOW!!!");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 420, 40));

        lprice.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jPanel2.add(lprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 140, 30));

        tperson.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tperson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpersonActionPerformed(evt);
            }
        });
        jPanel2.add(tperson, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 160, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel4.setText("Select Packages:-");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 130, 30));

        tpackage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tpackage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gold", "silver", "bronze", " " }));
        tpackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpackageActionPerformed(evt);
            }
        });
        jPanel2.add(tpackage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 110, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel5.setText("Total Persons:-");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 110, 28));

        tdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.add(tdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 180, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel7.setText("Phone No. :-");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 90, 30));

        tcontact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcontactActionPerformed(evt);
            }
        });
        jPanel2.add(tcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 300, -1));

        jButton1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, 100, 40));

        tdestination.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.add(tdestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 90, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel8.setText("Date  :-");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 60, 20));

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel10.setText("Amount :-");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 90, 20));

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel12.setText("To");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        jLabel11.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel11.setText("Destination:-");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CONFIRM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 120, 40));

        tname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnameActionPerformed(evt);
            }
        });
        jPanel2.add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 300, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel6.setText("Customer name:-");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 140, 30));

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Check Price");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, -1));

        tto.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        tto.setText("Oooty");
        jPanel2.add(tto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 66, 561, 620));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/application/Imgs/wp4922106 (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, -4, 1377, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tpersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpersonActionPerformed

    private void tpackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpackageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpackageActionPerformed

    private void tcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcontactActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Oooty k = new Oooty();
        k.show();

        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Travelmanagement","root","Manish6022@");

            String query="insert into booking(customername,contactnumber,destination,T_O,people,packagename,totalprice,traveldate) values(?,?,?,?,?,?,?,?)";
            PreparedStatement ps=con.prepareStatement(query);

            ps.setString(1,tname.getText());
            ps.setString(2,tcontact.getText());
            ps.setString(3,tdestination.getText());
            ps.setString(4, tto.getText());
            ps.setString(5, (String) tperson.getText());
            ps.setString(6, (String) tpackage.getSelectedItem());
            ps.setString(7,lprice.getText());
            ps.setString(8,tdate.getText());
            int  i = ps.executeUpdate();
            Receipt rk =new Receipt();
            rk.show();

            dispose();
            JOptionPane.showMessageDialog(this,"record has succefully Stored");
            ps.close();
            con.close();

        }catch(Exception e1){
            e1.printStackTrace();
            JOptionPane.showMessageDialog(null, "error");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String p = (String)tpackage.getSelectedItem();
        String d=(String)tdestination.getText();
        String t=(String)tto.getText();

        int cost = 0;
        if(p.equals("Gold")&&d.equals("Mumbai")&&t.equals("Goa")) {
            cost+=1000;
            cost+=32000;
        }
        if(p.equals("Gold")&&d.equals("Goa")&&t.equals("Mumbai")) {
            cost+=1000;
            cost+=32000;
        }
        if(p.equals("Gold")&&d.equals("Mumbai")&&t.equals("Rajasthan")){
            cost+=3000;
            cost+=32000;
        }
        if(p.equals("Gold")&&d.equals("Rajasthan")&&t.equals("Mumbai")){
            cost+=3000;
            cost+=32000;
        }

        if(p.equals("Gold")&&d.equals("Mumbai")&&t.equals("Himachal")) {
            cost=32000;
            cost+=10000;
        }
        if(p.equals("Gold")&&d.equals("Himachal")&&t.equals("Mumbai")) {
            cost=32000;
            cost+=10000;
        }
        if(p.equals("Gold")&&d.equals("Mumbai")&&t.equals("Delhi")) {
            cost=32000;
            cost+=5000;
        }
        if(p.equals("Gold")&&d.equals("Delhi")&&t.equals("Mumbai")) {
            cost+=5000;
            cost+=32000;
        }
        if(p.equals("Gold")&&d.equals("Oooty")&&t.equals("Mumbai")) {
            cost=32000;
            cost+=5000;
        }
        if(p.equals("Gold")&&d.equals("Mumbai")&&t.equals("Oooty")) {
            cost=32000;
            cost+=5000;
        }
        if(p.equals("Gold")&&d.equals("Kolkata")&&t.equals("Mumbai")) {
            cost=32000;
            cost+=4000;
        }
        if(p.equals("Gold")&&d.equals("Mumbai")&&t.equals("Kolkata")) {
            cost=32000;
            cost+=4000;
        }
        if(p.equals("Gold")&&d.equals("Kashmir")&&t.equals("Mumbai")) {
            cost=32000;
            cost+=10000;
        }
        if(p.equals("Gold")&&d.equals("Mumbai")&&t.equals("Kashmir")) {
            cost=32000;
            cost+=10000;
        }
        if(p.equals("Gold")&&d.equals("Mumbai")&&t.equals("Kerla")) {
            cost=32000;
            cost+=3000;
        }
        if(p.equals("Gold")&&d.equals("Kerla")&&t.equals("Mumbai")) {
            cost=32000;
            cost+=3000;
        }
        if(p.equals("Gold")&&d.equals("Goa")&&t.equals("Himachal")) {
            cost=32000;
            cost+=11000;
        }
        if(p.equals("Gold")&&d.equals("Himachal")&&t.equals("Goa")) {
            cost=32000;
            cost+=11000;
        }
        if(p.equals("Gold")&&d.equals("Rajasthan")&&t.equals("Goa")) {
            cost=32000;
            cost+=3500;
        }
        if(p.equals("Gold")&&d.equals("Goa")&&t.equals("Rajasthan")) {
            cost=32000;
            cost+=3500;
        }
        if(p.equals("Gold")&&d.equals("Goa")&&t.equals("Delhi")) {
            cost=32000;
            cost+=5000;
        }
        if(p.equals("Gold")&&d.equals("Delhi")&&t.equals("Goa")) {
            cost=32000;
            cost+=5000;
        }
        if(p.equals("Gold")&&d.equals("Oooty")&&t.equals("Goa")) {
            cost=32000;
            cost+=6000;
        }
        if(p.equals("Gold")&&d.equals("Goa")&&t.equals("Oooty")) {
            cost=32000;
            cost+=6000;
        }
        if(p.equals("Gold")&&d.equals("Goa")&&t.equals("Kolkata")) {
            cost=32000;
            cost+=3000;
        }
        if(p.equals("Gold")&&d.equals("Kolkata")&&t.equals("Goa")) {
            cost=32000;
            cost+=3000;
        }
        if(p.equals("Gold")&&d.equals("Goa")&&t.equals("Kolkata")) {
            cost=32000;
            cost+=3000;
        }
        if(p.equals("Gold")&&d.equals("Kashmir")&&t.equals("Goa")) {
            cost=32000;
            cost+=12000;
        }
        if(p.equals("Gold")&&d.equals("Goa")&&t.equals("Kashmir")) {
            cost=32000;
            cost+=12000;
        }
        if(p.equals("Gold")&&d.equals("Goa")&&t.equals("Kerla")) {
            cost=32000;
            cost+=9000;
        }
        if(p.equals("Gold")&&d.equals("Kerla")&&t.equals("Goa")) {
            cost=32000;
            cost+=9000;
        }
        if(p.equals("Gold")&&d.equals("Himachal")&&t.equals("Rajasthan")) {
            cost=32000;
            cost+=4000;
        }
        if(p.equals("Gold")&&d.equals("Rajasthan")&&t.equals("Himachal")) {
            cost=32000;
            cost+=4000;
        }
        if(p.equals("Gold")&&d.equals("Himachal")&&t.equals("Delhi")) {
            cost=32000;
            cost+=4000;
        }
        if(p.equals("Gold")&&d.equals("Delhi")&&t.equals("Himachal")) {
            cost=32000;
            cost+=4000;
        }
        if(p.equals("Gold")&&d.equals("Himachal")&&t.equals("Delhi")) {
            cost=32000;
            cost+=4000;
        }
        if((p.equals("Gold")&&d.equals("Oooty")&&t.equals("Himachal"))||(p.equals("Gold")&&d.equals("Himachal")&&t.equals("Oooty"))) {
            cost=32000;
            cost+=5000;
        }
        if((p.equals("Gold")&&d.equals("Kolkata")&&t.equals("Himachal"))||(p.equals("Gold")&&d.equals("Himachal")&&t.equals("Kolkata"))) {
            cost=32000;
            cost+=2000;
        }
        if((p.equals("Gold")&&d.equals("Kashmir")&&t.equals("Himachal"))||(p.equals("Gold")&&d.equals("Himachal")&&t.equals("Kashmir"))) {
            cost=32000;
            cost+=1000;
        }

        if((p.equals("Gold")&&d.equals("Kerla")&&t.equals("Himachal"))||(p.equals("Gold")&&d.equals("Himachal")&&t.equals("Kerla"))) {
            cost=32000;
            cost+=12000;
        }
        if((p.equals("Gold")&&d.equals("Rajasthan")&&t.equals("Delhi"))||(p.equals("Gold")&&d.equals("Delhi")&&t.equals("Rajasthan"))) {
            cost=32000;
            cost+=3000;
        }
        if((p.equals("Gold")&&d.equals("Rajasthan")&&t.equals("Oooty"))||(p.equals("Gold")&&d.equals("Oooty")&&t.equals("Rajasthan"))) {
            cost=32000;
            cost+=5000;
        }
        if((p.equals("Gold")&&d.equals("Rajasthan")&&t.equals("Kolkata"))||(p.equals("Gold")&&d.equals("Kolkata")&&t.equals("Rajasthan"))) {
            cost=32000;
            cost+=12000;
        }
        if((p.equals("Gold")&&d.equals("Rajasthan")&&t.equals("Kashmir"))||(p.equals("Gold")&&d.equals("Kashmir")&&t.equals("Rajasthan"))) {
            cost=32000;
            cost+=3000;
        }
        if((p.equals("Gold")&&d.equals("Rajasthan")&&t.equals("Kerla"))||(p.equals("Gold")&&d.equals("Kerla")&&t.equals("Rajasthan"))) {
            cost=32000;
            cost+=5000;
        }
        if((p.equals("Gold")&&d.equals("Delhi")&&t.equals("Oooty"))||(p.equals("Gold")&&d.equals("Oooty")&&t.equals("Delhi"))) {
            cost=32000;
            cost+=5000;
        }
        if((p.equals("Gold")&&d.equals("Delhi")&&t.equals("Kolkata"))||(p.equals("Gold")&&d.equals("Kolkata")&&t.equals("Delhi"))) {
            cost=32000;
            cost+=12000;
        }
        if((p.equals("Gold")&&d.equals("Delhi")&&t.equals("Kashmir"))||(p.equals("Gold")&&d.equals("Kashmir")&&t.equals("Delhi"))) {
            cost=32000;
            cost+=5000;
        }
        if((p.equals("Gold")&&d.equals("Delhi")&&t.equals("Kerla"))||(p.equals("Gold")&&d.equals("Kerla")&&t.equals("Delhi"))) {
            cost=32000;
            cost+=11000;
        }
        if((p.equals("Gold")&&d.equals("Oooty")&&t.equals("Kolkata"))||(p.equals("Gold")&&d.equals("Kolkata")&&t.equals("Oooty"))) {
            cost=32000;
            cost+=5000;
        }
        if((p.equals("Gold")&&d.equals("Oooty")&&t.equals("Kashmir"))||(p.equals("Gold")&&d.equals("Kashmir")&&t.equals("Oooty"))) {
            cost=32000;
            cost+=5000;
        }
        if((p.equals("Gold")&&d.equals("Oooty")&&t.equals("Kerla"))||(p.equals("Gold")&&d.equals("Kerla")&&t.equals("Oooty"))) {
            cost=32000;
            cost+=5000;
        }
        if((p.equals("Gold")&&d.equals("Kolkata")&&t.equals("Kashmir"))||(p.equals("Gold")&&d.equals("Kashmir")&&t.equals("Kolkata"))) {
            cost=32000;
            cost+=4000;
        }
        if((p.equals("Gold")&&d.equals("Kolkata")&&t.equals("Kerla"))||(p.equals("Gold")&&d.equals("Kerla")&&t.equals("Kolkata"))) {
            cost=32000;
            cost+=10000;
        }
        if((p.equals("Gold")&&d.equals("Kashmir")&&t.equals("Kerla"))||(p.equals("Gold")&&d.equals("Kerla")&&t.equals("Kashmir"))) {
            cost=32000;
            cost+=10000;
        }

        //Silver
        if(p.equals("silver")&&d.equals("Mumbai")&&t.equals("Goa")) {
            cost+=400;
            cost+=25000;
        }
        if(p.equals("silver")&&d.equals("Goa")&&t.equals("Mumbai")) {
            cost+=400;
            cost+=25000;
        }
        if(p.equals("silver")&&d.equals("Mumbai")&&t.equals("Rajasthan")){
            cost+=800;
            cost+=25000;
        }
        if(p.equals("silver")&&d.equals("Rajasthan")&&t.equals("Mumbai")){
            cost+=800;
            cost+=25000;
        }

        if(p.equals("silver")&&d.equals("Mumbai")&&t.equals("Himachal")) {
            cost=25000;
            cost+=1000;
        }
        if(p.equals("silver")&&d.equals("Himachal")&&t.equals("Mumbai")) {
            cost=25000;
            cost+=1000;
        }
        if(p.equals("silver")&&d.equals("Mumbai")&&t.equals("Delhi")) {
            cost=25000;
            cost+=1500;
        }
        if(p.equals("silver")&&d.equals("Delhi")&&t.equals("Mumbai")) {
            cost+=1500;
            cost+=25000;
        }
        if(p.equals("silver")&&d.equals("Oooty")&&t.equals("Mumbai")) {
            cost=25000;
            cost+=500;
        }
        if(p.equals("silver")&&d.equals("Mumbai")&&t.equals("Oooty")) {
            cost=25000;
            cost+=500;
        }
        if(p.equals("silver")&&d.equals("Kolkata")&&t.equals("Mumbai")) {
            cost=25000;
            cost+=800;
        }
        if(p.equals("silver")&&d.equals("Mumbai")&&t.equals("Kolkata")) {
            cost=25000;
            cost+=800;
        }
        if(p.equals("silver")&&d.equals("Kashmir")&&t.equals("Mumbai")) {
            cost=25000;
            cost+=2000;
        }
        if(p.equals("silver")&&d.equals("Mumbai")&&t.equals("Kashmir")) {
            cost=25000;
            cost+=2000;
        }
        if(p.equals("silver")&&d.equals("Mumbai")&&t.equals("Kerla")) {
            cost=25000;
            cost+=600;
        }
        if(p.equals("silver")&&d.equals("Kerla")&&t.equals("Mumbai")) {
            cost=25000;
            cost+=600;
        }
        if(p.equals("silver")&&d.equals("Goa")&&t.equals("Himachal")) {
            cost=25000;
            cost+=1500;
        }
        if(p.equals("silver")&&d.equals("Himachal")&&t.equals("Goa")) {
            cost=25000;
            cost+=1500;
        }
        if(p.equals("silver")&&d.equals("Rajasthan")&&t.equals("Goa")) {
            cost=25000;
            cost+=800;
        }
        if(p.equals("silver")&&d.equals("Goa")&&t.equals("Rajasthan")) {
            cost=25000;
            cost+=800;
        }
        if(p.equals("silver")&&d.equals("Goa")&&t.equals("Delhi")) {
            cost=25000;
            cost+=1000;
        }
        if(p.equals("silver")&&d.equals("Delhi")&&t.equals("Goa")) {
            cost=25000;
            cost+=1000;
        }
        if(p.equals("silver")&&d.equals("Oooty")&&t.equals("Goa")) {
            cost=25000;
            cost+=500;
        }
        if(p.equals("silver")&&d.equals("Goa")&&t.equals("Oooty")) {
            cost=25000;
            cost+=500;
        }
        if(p.equals("silver")&&d.equals("Goa")&&t.equals("Kolkata")) {
            cost=25000;
            cost+=500;
        }
        if(p.equals("silver")&&d.equals("Kolkata")&&t.equals("Goa")) {
            cost=25000;
            cost+=600;
        }
        if(p.equals("silver")&&d.equals("Goa")&&t.equals("Kolkata")) {
            cost=25000;
            cost+=600;
        }
        if(p.equals("silver")&&d.equals("Kashmir")&&t.equals("Goa")) {
            cost=25000;
            cost+=1000;
        }
        if(p.equals("silver")&&d.equals("Goa")&&t.equals("Kashmir")) {
            cost=25000;
            cost+=1000;
        }
        if(p.equals("silver")&&d.equals("Goa")&&t.equals("Kerla")) {
            cost=25000;
            cost+=700;
        }
        if(p.equals("silver")&&d.equals("Kerla")&&t.equals("Goa")) {
            cost=25000;
            cost+=700;
        }
        if(p.equals("silver")&&d.equals("Himachal")&&t.equals("Rajasthan")) {
            cost=25000;
            cost+=400;
        }
        if(p.equals("silver")&&d.equals("Rajasthan")&&t.equals("Himachal")) {
            cost=25000;
            cost+=400;
        }
        if(p.equals("silver")&&d.equals("Himachal")&&t.equals("Delhi")) {
            cost=25000;
            cost+=500;
        }
        if(p.equals("silver")&&d.equals("Delhi")&&t.equals("Himachal")) {
            cost=25000;
            cost+=500;
        }
        if(p.equals("silver")&&d.equals("Himachal")&&t.equals("Delhi")) {
            cost=25000;
            cost+=500;
        }
        if((p.equals("silver")&&d.equals("Oooty")&&t.equals("Himachal"))||(p.equals("silver")&&d.equals("Himachal")&&t.equals("Oooty"))) {
            cost=25000;
            cost+=500;
        }
        if((p.equals("silver")&&d.equals("Kolkata")&&t.equals("Himachal"))||(p.equals("silver")&&d.equals("Himachal")&&t.equals("Kolkata"))) {
            cost=25000;
            cost+=2000;
        }
        if((p.equals("silver")&&d.equals("Kashmir")&&t.equals("Himachal"))||(p.equals("silver")&&d.equals("Himachal")&&t.equals("Kashmir"))) {
            cost=25000;
            cost+=400;
        }

        if((p.equals("silver")&&d.equals("Kerla")&&t.equals("Himachal"))||(p.equals("silver")&&d.equals("Himachal")&&t.equals("Kerla"))) {
            cost=25000;
            cost+=3000;
        }
        if((p.equals("silver")&&d.equals("Rajasthan")&&t.equals("Delhi"))||(p.equals("silver")&&d.equals("Delhi")&&t.equals("Rajasthan"))) {
            cost=25000;
            cost+=600;
        }
        if((p.equals("silver")&&d.equals("Rajasthan")&&t.equals("Oooty"))||(p.equals("silver")&&d.equals("Oooty")&&t.equals("Rajasthan"))) {
            cost=25000;
            cost+=500;
        }
        if((p.equals("silver")&&d.equals("Rajasthan")&&t.equals("Kolkata"))||(p.equals("silver")&&d.equals("Kolkata")&&t.equals("Rajasthan"))) {
            cost=25000;
            cost+=500;
        }
        if((p.equals("silver")&&d.equals("Rajasthan")&&t.equals("Kashmir"))||(p.equals("silver")&&d.equals("Kashmir")&&t.equals("Rajasthan"))) {
            cost=25000;
            cost+=600;
        }
        if((p.equals("silver")&&d.equals("Rajasthan")&&t.equals("Kerla"))||(p.equals("silver")&&d.equals("Kerla")&&t.equals("Rajasthan"))) {
            cost=25000;
            cost+=800;
        }
        if((p.equals("silver")&&d.equals("Delhi")&&t.equals("Oooty"))||(p.equals("silver")&&d.equals("Oooty")&&t.equals("Delhi"))) {
            cost=25000;
            cost+=500;
        }
        if((p.equals("silver")&&d.equals("Delhi")&&t.equals("Kolkata"))||(p.equals("silver")&&d.equals("Kolkata")&&t.equals("Delhi"))) {
            cost=25000;
            cost+=3000;
        }
        if((p.equals("silver")&&d.equals("Delhi")&&t.equals("Kashmir"))||(p.equals("silver")&&d.equals("Kashmir")&&t.equals("Delhi"))) {
            cost=25000;
            cost+=400;
        }
        if((p.equals("silver")&&d.equals("Delhi")&&t.equals("Kerla"))||(p.equals("silver")&&d.equals("Kerla")&&t.equals("Delhi"))) {
            cost=25000;
            cost+=2000;
        }
        if((p.equals("silver")&&d.equals("Oooty")&&t.equals("Kolkata"))||(p.equals("silver")&&d.equals("Kolkata")&&t.equals("Oooty"))) {
            cost=25000;
            cost+=500;
        }
        if((p.equals("silver")&&d.equals("Oooty")&&t.equals("Kashmir"))||(p.equals("silver")&&d.equals("Kashmir")&&t.equals("Oooty"))) {
            cost=25000;
            cost+=500;
        }
        if((p.equals("silver")&&d.equals("Oooty")&&t.equals("Kerla"))||(p.equals("silver")&&d.equals("Kerla")&&t.equals("Oooty"))) {
            cost=25000;
            cost+=500;
        }
        if((p.equals("silver")&&d.equals("Kolkata")&&t.equals("Kashmir"))||(p.equals("silver")&&d.equals("Kashmir")&&t.equals("Kolkata"))) {
            cost=25000;
            cost+=500;
        }
        if((p.equals("silver")&&d.equals("Kolkata")&&t.equals("Kerla"))||(p.equals("silver")&&d.equals("Kerla")&&t.equals("Kolkata"))) {
            cost=25000;
            cost+=400;
        }
        if((p.equals("silver")&&d.equals("Kashmir")&&t.equals("Kerla"))||(p.equals("silver")&&d.equals("Kerla")&&t.equals("Kashmir"))) {
            cost=25000;
            cost+=1000;
        }
        //broze
        if(p.equals("bronze")&&d.equals("Mumbai")&&t.equals("Goa")) {
            cost+=400;
            cost+=12000;
        }
        if(p.equals("bronze")&&d.equals("Goa")&&t.equals("Mumbai")) {
            cost+=400;
            cost+=12000;
        }
        if(p.equals("bronze")&&d.equals("Mumbai")&&t.equals("Rajasthan")){
            cost+=800;
            cost+=12000;
        }
        if(p.equals("bronze")&&d.equals("Rajasthan")&&t.equals("Mumbai")){
            cost+=800;
            cost+=12000;
        }

        if(p.equals("bronze")&&d.equals("Mumbai")&&t.equals("Himachal")) {
            cost=12000;
            cost+=1000;
        }
        if(p.equals("bronze")&&d.equals("Himachal")&&t.equals("Mumbai")) {
            cost=12000;
            cost+=1000;
        }
        if(p.equals("bronze")&&d.equals("Mumbai")&&t.equals("Delhi")) {
            cost=12000;
            cost+=1500;
        }
        if(p.equals("bronze")&&d.equals("Delhi")&&t.equals("Mumbai")) {
            cost+=1500;
            cost+=12000;
        }
        if(p.equals("bronze")&&d.equals("Oooty")&&t.equals("Mumbai")) {
            cost=12000;
            cost+=500;
        }
        if(p.equals("bronze")&&d.equals("Mumbai")&&t.equals("Oooty")) {
            cost=12000;
            cost+=500;
        }
        if(p.equals("bronze")&&d.equals("Kolkata")&&t.equals("Mumbai")) {
            cost=12000;
            cost+=800;
        }
        if(p.equals("bronze")&&d.equals("Mumbai")&&t.equals("Kolkata")) {
            cost=12000;
            cost+=800;
        }
        if(p.equals("bronze")&&d.equals("Kashmir")&&t.equals("Mumbai")) {
            cost=12000;
            cost+=2000;
        }
        if(p.equals("bronze")&&d.equals("Mumbai")&&t.equals("Kashmir")) {
            cost=12000;
            cost+=2000;
        }
        if(p.equals("bronze")&&d.equals("Mumbai")&&t.equals("Kerla")) {
            cost=12000;
            cost+=600;
        }
        if(p.equals("bronze")&&d.equals("Kerla")&&t.equals("Mumbai")) {
            cost=12000;
            cost+=600;
        }
        if(p.equals("bronze")&&d.equals("Goa")&&t.equals("Himachal")) {
            cost=12000;
            cost+=1500;
        }
        if(p.equals("bronze")&&d.equals("Himachal")&&t.equals("Goa")) {
            cost=12000;
            cost+=1500;
        }
        if(p.equals("bronze")&&d.equals("Rajasthan")&&t.equals("Goa")) {
            cost=12000;
            cost+=800;
        }
        if(p.equals("bronze")&&d.equals("Goa")&&t.equals("Rajasthan")) {
            cost=12000;
            cost+=800;
        }
        if(p.equals("bronze")&&d.equals("Goa")&&t.equals("Delhi")) {
            cost=12000;
            cost+=1000;
        }
        if(p.equals("bronze")&&d.equals("Delhi")&&t.equals("Goa")) {
            cost=12000;
            cost+=1000;
        }
        if(p.equals("bronze")&&d.equals("Oooty")&&t.equals("Goa")) {
            cost=12000;
            cost+=500;
        }
        if(p.equals("bronze")&&d.equals("Goa")&&t.equals("Oooty")) {
            cost=12000;
            cost+=500;
        }
        if(p.equals("bronze")&&d.equals("Goa")&&t.equals("Kolkata")) {
            cost=12000;
            cost+=500;
        }
        if(p.equals("bronze")&&d.equals("Kolkata")&&t.equals("Goa")) {
            cost=12000;
            cost+=600;
        }
        if(p.equals("bronze")&&d.equals("Goa")&&t.equals("Kolkata")) {
            cost=12000;
            cost+=600;
        }
        if(p.equals("bronze")&&d.equals("Kashmir")&&t.equals("Goa")) {
            cost=12000;
            cost+=1000;
        }
        if(p.equals("bronze")&&d.equals("Goa")&&t.equals("Kashmir")) {
            cost=12000;
            cost+=1000;
        }
        if(p.equals("bronze")&&d.equals("Goa")&&t.equals("Kerla")) {
            cost=12000;
            cost+=700;
        }
        if(p.equals("bronze")&&d.equals("Kerla")&&t.equals("Goa")) {
            cost=12000;
            cost+=700;
        }
        if(p.equals("bronze")&&d.equals("Himachal")&&t.equals("Rajasthan")) {
            cost=12000;
            cost+=400;
        }
        if(p.equals("bronze")&&d.equals("Rajasthan")&&t.equals("Himachal")) {
            cost=12000;
            cost+=400;
        }
        if(p.equals("bronze")&&d.equals("Himachal")&&t.equals("Delhi")) {
            cost=12000;
            cost+=500;
        }
        if(p.equals("bronze")&&d.equals("Delhi")&&t.equals("Himachal")) {
            cost=12000;
            cost+=500;
        }
        if(p.equals("bronze")&&d.equals("Himachal")&&t.equals("Delhi")) {
            cost=12000;
            cost+=500;
        }
        if((p.equals("bronze")&&d.equals("Oooty")&&t.equals("Himachal"))||(p.equals("bronze")&&d.equals("Himachal")&&t.equals("Oooty"))) {
            cost=12000;
            cost+=500;
        }
        if((p.equals("bronze")&&d.equals("Kolkata")&&t.equals("Himachal"))||(p.equals("bronze")&&d.equals("Himachal")&&t.equals("Kolkata"))) {
            cost=12000;
            cost+=2000;
        }
        if((p.equals("bronze")&&d.equals("Kashmir")&&t.equals("Himachal"))||(p.equals("bronze")&&d.equals("Himachal")&&t.equals("Kashmir"))) {
            cost=12000;
            cost+=400;
        }

        if((p.equals("bronze")&&d.equals("Kerla")&&t.equals("Himachal"))||(p.equals("bronze")&&d.equals("Himachal")&&t.equals("Kerla"))) {
            cost=12000;
            cost+=3000;
        }
        if((p.equals("bronze")&&d.equals("Rajasthan")&&t.equals("Delhi"))||(p.equals("bronze")&&d.equals("Delhi")&&t.equals("Rajasthan"))) {
            cost=12000;
            cost+=600;
        }
        if((p.equals("bronze")&&d.equals("Rajasthan")&&t.equals("Oooty"))||(p.equals("bronze")&&d.equals("Oooty")&&t.equals("Rajasthan"))) {
            cost=12000;
            cost+=500;
        }
        if((p.equals("bronze")&&d.equals("Rajasthan")&&t.equals("Kolkata"))||(p.equals("bronze")&&d.equals("Kolkata")&&t.equals("Rajasthan"))) {
            cost=12000;
            cost+=500;
        }
        if((p.equals("bronze")&&d.equals("Rajasthan")&&t.equals("Kashmir"))||(p.equals("bronze")&&d.equals("Kashmir")&&t.equals("Rajasthan"))) {
            cost=12000;
            cost+=600;
        }
        if((p.equals("bronze")&&d.equals("Rajasthan")&&t.equals("Kerla"))||(p.equals("bronze")&&d.equals("Kerla")&&t.equals("Rajasthan"))) {
            cost=12000;
            cost+=800;
        }
        if((p.equals("bronze")&&d.equals("Delhi")&&t.equals("Oooty"))||(p.equals("bronze")&&d.equals("Oooty")&&t.equals("Delhi"))) {
            cost=12000;
            cost+=500;
        }
        if((p.equals("bronze")&&d.equals("Delhi")&&t.equals("Kolkata"))||(p.equals("bronze")&&d.equals("Kolkata")&&t.equals("Delhi"))) {
            cost=12000;
            cost+=3000;
        }
        if((p.equals("bronze")&&d.equals("Delhi")&&t.equals("Kashmir"))||(p.equals("bronze")&&d.equals("Kashmir")&&t.equals("Delhi"))) {
            cost=12000;
            cost+=400;
        }
        if((p.equals("bronze")&&d.equals("Delhi")&&t.equals("Kerla"))||(p.equals("bronze")&&d.equals("Kerla")&&t.equals("Delhi"))) {
            cost=12000;
            cost+=2000;
        }
        if((p.equals("bronze")&&d.equals("Oooty")&&t.equals("Kolkata"))||(p.equals("bronze")&&d.equals("Kolkata")&&t.equals("Oooty"))) {
            cost=12000;
            cost+=500;
        }
        if((p.equals("bronze")&&d.equals("Oooty")&&t.equals("Kashmir"))||(p.equals("bronze")&&d.equals("Kashmir")&&t.equals("Oooty"))) {
            cost=12000;
            cost+=500;
        }
        if((p.equals("bronze")&&d.equals("Oooty")&&t.equals("Kerla"))||(p.equals("bronze")&&d.equals("Kerla")&&t.equals("Oooty"))) {
            cost=12000;
            cost+=500;
        }
        if((p.equals("bronze")&&d.equals("Kolkata")&&t.equals("Kashmir"))||(p.equals("bronze")&&d.equals("Kashmir")&&t.equals("Kolkata"))) {
            cost=12000;
            cost+=500;
        }
        if((p.equals("bronze")&&d.equals("Kolkata")&&t.equals("Kerla"))||(p.equals("bronze")&&d.equals("Kerla")&&t.equals("Kolkata"))) {
            cost=12000;
            cost+=400;
        }
        if((p.equals("bronze")&&d.equals("Kashmir")&&t.equals("Kerla"))||(p.equals("bronze")&&d.equals("Kerla")&&t.equals("Kashmir"))) {
            cost=12000;
            cost+=1000;
        }

        cost *= Integer.parseInt((String)tperson.getText());

        lprice.setText("Rs "+cost);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookingooty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookingooty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookingooty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookingooty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookingooty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lprice;
    private javax.swing.JTextField tcontact;
    private javax.swing.JTextField tdate;
    private javax.swing.JTextField tdestination;
    private javax.swing.JTextField tname;
    private javax.swing.JComboBox<String> tpackage;
    private javax.swing.JTextField tperson;
    private javax.swing.JLabel tto;
    // End of variables declaration//GEN-END:variables
}
